### ISSUE TITLE
Could not perform stairs detection: Depth image has unsupported encoding: 32FC1

### ISSUE THREAD

**Issue by charon-cheung** [mdrwiega/depth_nav_tools#15]
when I run cliff_detector, I got this error, it's in function CliffDetectorNode::depthCb  line_58, what encoding does this node want ?

**Comment by rahulmoorthy19** [comment]
If at all anyone faces the same issue in the future...I had the same issue while running depth_sensor_pose....by reading the code I found out that it needs 16UC1...maybe you can try with that

**Comment by mdrwiega** [comment]
Now the 32FC1 image encoding is supported by cliff_detector and depth_sensor_pose.
