### ISSUE TITLE
Commit 5e07d3f Breaks Operation

### ISSUE THREAD

**Issue by madgrizzle** [mdrwiega/depth_nav_tools#16]
I left a comment in commit 5e07d3f (the last one) for laserscan_kinect, but it applies to other files like cliff_detector and pose_estimator.

It looks like the callback when the scan topic is subscribed to includes a test that is always false:

> sub_ != nullptr

The previous code tested 
> !sub

The change always tests false since initially sub_ is a nullptr.  Since that's the case, it never gets set to subscribe to image and therefore, there is never a callback to publish the scan message.

In my copy, I changed it to

>sub_ == nullptr

and it worked.  Whether or not that is the proper way to do it, I don't know..

**Comment by mdrwiega** [comment]
Thank you. I'll fix it.
