### ISSUE TITLE
nav_layer_from_points not working

### ISSUE THREAD

**Issue by David9696** [mdrwiega/depth_nav_tools#3]
Hi,

I am to add your nav_layer_from_points plug-in to our robot's global costmap. But we get the following errors:

Using plugin "simplelayer"
terminate called after throwing an instance of 'pluginlib::CreateClassException'
  what():  MultiLibraryClassLoader: Could not create object of class type nav_layer_from_points::NavLayerPoints as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()

My global_costmap.yaml is listed as follows:

global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 5.0
  static_map: true

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: simplelayer,        type: "nav_layer_from_points::NavLayerPoints"}

Could you please enlighten me how to solve this problem?

Thanks.

**Comment by gersonos** [comment]
Hi david, have you solved this problem?

I mean, I'm trying to add this layer to my costmap this way, and also by executing the three necessary nodes (cliff_detector, laserscan and depth_sensor_pose) without success. I feel I'm close to have something for local_costmap detecting it.

Thanks!

**Comment by HUDiwan** [comment]
Hello,

Have you been able to solve this issue?

**Comment by HUDiwan** [comment]
Hey, 

You could fix this issue by going into the plugin.xml file and changing 

<class type="nav_layer_from_points::NavLayerFromPoints" base_class_type="costmap_2d::Layer"><description>Uses points information to change the costmap</description>

with,
<class type="nav_layer_from_points::NavLayerFromPoints" base_class_type="costmap_2d::Layer"><description>Uses points information to change the costmap</description></class>
</class>

This will solve the issue. The pull request has been made, so it will be fixed on package soon.

Regards,
HUDiwan
