### ISSUE TITLE
Error when depth_pose is implemented

### ISSUE THREAD

**Issue by HUDiwan** [mdrwiega/depth_nav_tools#9]
Hello,

I am trying to use this package for stair detection. When I run all the nodes I get this error:

[ERROR] [1553614236.245436569]: Ground points not detected
[ERROR] [1553614236.245497004]: height = 0.0000 angle = 0.0000

Any idea how I can fix it?

Thanks,
Heta

**Comment by xiaoxiaotao** [comment]
Do you solve it? I have the same issue. Thank you!

**Comment by mdrwiega** [comment]
Hi, have you correctly configured the node? I mean especially sensor mount height and sensor tilt?

**Comment by mdrwiega** [comment]
I have added new debug image which shows currently searched area and selected ground points.It can be enable by set to true a parameter `publish_dbg_info`.
